imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
    - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }
    
editor:
   config:
      contentsCss: ["EXT:rte_ckeditor/Resources/Public/Css/contents.css", "EXT:armtemplate/Resources/Public/Css/rte.css"]
      
      format_tags: "div;p;h1;h2;h3;h4;h5;h6;pre;i"
      
      stylesSet:
        # block level styles
        - { name: "align-left", element: ['h1', 'h2', 'h3', 'h4','h5', 'h6', 'div', 'p', 'td', 'th'], attributes: { 'class': 'align-left' }}
        - { name: "align-center", element: ['h1', 'h2', 'h3', 'h4','h5', 'h6', 'div', 'p', 'td', 'th'], attributes: { 'class': 'align-center' }}
        - { name: "align-right", element: ['h1', 'h2', 'h3', 'h4','h5', 'h6', 'div', 'p', 'td', 'th'], attributes: { 'class': 'align-right' }}
        - { name: "align-justify", element: ['h1', 'h2', 'h3', 'h4','h5', 'h6', 'div', 'p', 'td', 'th'], attributes: { 'class': 'align-justify' }}
        - { name: "text-center", element: ['h1', 'h2', 'h3', 'h4','h5', 'h6', 'div', 'p', 'td', 'th'], attributes: { 'class': 'text-center' }}
        - { name: "row", element: "div", attributes: { 'class': 'row' }}
        - { name: "col-sm-6", element: "div", attributes: { 'class': 'col-sm-6' }}
        - { name: "col-md-3", element: "div", attributes: { 'class': 'col-md-3' }}
        - { name: "productGrid", element: "div", attributes: { 'class': 'productGrid' }}
        - { name: "titleName", element: "div", attributes: { 'class': 'titleName' }}
        - { name: "table-responsive", element: "div", attributes: { 'class': 'table-responsive' }}
        - { name: "table", element: "table", attributes: { 'class': 'table' }}
        - { name: "table-bordered", element: "table", attributes: { 'class': 'table-bordered' }}
        - { name: "fa-container", element: ["div", "p"], attributes: { 'class': 'fa-container' }}
        - { name: "prodCol", element: ["div", "p"], attributes: { 'class': 'prodCol' }}
        - { name: "linkList", element: "ul", attributes: { 'class': 'linkList' }}
        - { name: "liarrows", element: ["div", "p", ul"], attributes: { 'class': 'liarrows' }}
        - { name: "button-link", element: ["p", 'span', "a"], attributes: { 'class': 'button-link' }}
        
        # Inline styles
        - { name: "btn", element: "a", attributes: { 'class': 'btn' }}
        - { name: "btn-primary", element: "a", attributes: { 'class': 'btn-primary' }}
        - { name: "btn-lg", element: "a", attributes: { 'class': 'btn-lg' }}
        - { name: "anchor-link", element: "a", attributes: { 'class': 'anchor-link' }}
        - { name: "btn-default", element: "a", attributes: { 'class': 'btn-default' }}
        - { name: "navbar-btn", element: "a", attributes: { 'class': 'navbar-btn' }}
        - { name: "fa", element: "i", attributes: { 'class': 'fa' }}
        - { name: "fa-3x", element: "i", attributes: { 'class': 'fa-3x' }}
        - { name: "fa-heart-o", element: "i", attributes: { 'class': 'fa-heart-o' }}
        - { name: "fa-comment-o", element: "i", attributes: { 'class': 'fa-comment-o' }}
        - { name: "fa-bell-o", element: "i", attributes: { 'class': 'fa-bell-o' }}
        
      toolbarGroups:
      - { name: clipboard, groups: [clipboard, undo] }
      - { name: editing,   groups: [find, selection, spellchecker] }
      - { name: insert }
      - { name: table }
      - { name: tabletools }
      - { name: document,  groups: [ mode, document, doctools ] }
      - "/"
      - { name: basicstyles, groups: [ basicstyles, align, cleanup ] }
      - { name: paragraph,   groups: [ list, indent, blocks, align, bidi ] }
      - { name: links }
      - "/"
      - { name: styles }
      - { name: others }
      
      extraPlugins:
        - justify
        - specialchar
        - showblocks
        - codesnippet
        
      externalPlugins:
        typo3image:
            allowedExtensions: "jpg,jpeg,png"
      
      
      justifyClasses:
      - align-left
      - align-center
      - align-right
      - align-justify
      
      removePlugins:

      removeButtons:

# Allow s and u tag
processing:
  allowTags:
    - s
    - u
    - i