imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
    - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }
    
editor:
   config:
      contentsCss: "EXT:armcookingtpl/Resources/Public/css/rte.css"
      
      stylesSet:
        - { name: "header ribbon", element: ['h1', 'h2', 'h3', 'h4','h5', 'h6', 'div', 'p'], attributes: { 'class': 'header-ribbon' }}
        - { name: "widget title", element: ['h1', 'h2', 'h3', 'h4','h5', 'h6', 'div', 'p'], attributes: { 'class': 'widget-title' }}
        - { name: "shortcode about author", element: "div", attributes: { 'class': 'shortcode-about-author' }}
        - { name: "widget", element: "div", attributes: { 'class': 'widget' }}
        - { name: "sci-title", element: "div", attributes: { 'class': 'sci-title' }}
        - { name: "sci-media", element: "div", attributes: { 'class': 'sci-media' }}
        - { name: "saa-content", element: "div", attributes: { 'class': 'saa-content' }}

      format_tags: "div;p;h1;h2;h3;h4;h5;h6;pre"
      
      toolbarGroups:
      - { name: clipboard, groups: [clipboard, undo] }
      - { name: editing,   groups: [find, selection, spellchecker] }
      - { name: insert }
      - { name: table }
      - { name: tabletools }
      - { name: document,  groups: [ mode, document, doctools ] }
      - "/"
      - { name: basicstyles, groups: [ basicstyles, align, cleanup ] }
      - { name: paragraph,   groups: [ list, indent, blocks, align, bidi ] }
      - { name: links }
      - "/"
      - { name: styles }
      - { name: others }
      
      extraPlugins:
        - justify
        - font
        - showblocks
        - codesnippet     
      
      justifyClasses:
      - align-left
      - align-center
      - align-right
      - align-justify
      
      removePlugins:

      removeButtons:

processing:
  allowTags:
    - s
    - u