<?php
/***************************************************************
 * Extension Manager/Repository config file for ext: "armtyposcript"
 *
 * Auto generated by Extension Builder 2017-04-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ARM TypoScript',
	'description' => 'Call typoscript object directly',
	'category' => 'plugin',
	'author' => 'ARM Technologies',
	'author_email' => 'anisur@armtechnologies.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);