<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "recipeblog"
 *
 * Auto generated by Extension Builder 2018-02-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'ARM Recipes',
    'description' => 'Recipe Blog extension',
    'category' => 'plugin',
    'author' => 'ARM Technologies',
    'author_email' => 'contact@armtechnologies.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
